---
- name: Download node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'

- name: Extract node_exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt
    remote_src: yes

- name: Create node_exporter user
  user:
    name: node_exporter
    system: yes
    create_home: no

- name: Install node_exporter binary
  command: cp /opt/node_exporter-1.7.0.linux-amd64/node_exporter /usr/local/bin/node_exporter
  args:
    creates: /usr/local/bin/node_exporter

- name: Create systemd service for node_exporter
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Prometheus Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      ExecStart=/usr/local/bin/node_exporter
      Restart=always

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable and start node_exporter
  service:
    name: node_exporter
    state: started
    enabled: true
